premio = float(input('Qual valor do premio total?'))
apost1 = float(input('Quanto o apostador 1 investiu?'))
apost2 = float(input('Quanto o apostador 2 investiu?'))
apost3 = float(input('Quanto o apostador 3 investiu?'))
apostatotal = (apost1+apost2+apost3)
porcentagem1 = (apost1/apostatotal)
porcentagem2 = (apost2/apostatotal)
porcentagem3 = (apost3/apostatotal)
premio1 = (porcentagem1 * premio)
premio2 = (porcentagem2 * premio)
premio3 = (porcentagem3 * premio)
print(f'O apostador 1 receberá {premio1} por sua participação de {porcentagem1}% na aposta total')
print(f'O apostador 2 receberá {premio2} por sua participação de {porcentagem2}% na aposta total')
print(f'O apostador 3 receberá {premio3} por sua participação de {porcentagem3}% na aposta total')